# Generated by Django 4.2.1 on 2023-08-22 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicprogram_name', models.CharField(default=None, max_length=100)),
                ('academicprogram_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default=None, max_length=100)),
                ('institution_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_firstname', models.CharField(default=None, max_length=100)),
                ('teacher_lastname', models.CharField(default=None, max_length=100)),
                ('teacher_number', models.IntegerField(unique=True)),
                ('teacher_institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='te_institution', to='schoolapp.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, max_length=100)),
                ('subject_number', models.IntegerField(unique=True)),
                ('subject_academicprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su_academicprogram', to='schoolapp.academicprogram')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su_teacher', to='schoolapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('student_lastname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('student_number', models.IntegerField(default=0)),
                ('student_academicprogram', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_academicprogram', to='schoolapp.academicprogram')),
                ('student_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_institution', to='schoolapp.institution')),
                ('student_subject', models.ManyToManyField(blank=True, related_name='st_subject', to='schoolapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_e1', models.FloatField(default=0.0)),
                ('grade_e2', models.FloatField(default=0.0)),
                ('grade_e3', models.FloatField(default=0.0)),
                ('grade_ef', models.FloatField(default=0.0)),
                ('grade_date', models.DateTimeField(default=datetime.datetime.now)),
                ('grade_student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_student', to='schoolapp.student')),
                ('grade_subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_subject', to='schoolapp.subject')),
                ('grade_teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_teacher', to='schoolapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='academicprogram_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_institution', to='schoolapp.institution'),
        ),
    ]
